### ISSUE TITLE
IAR Load Crash

### ISSUE THREAD

**Issue by TommyFDNY** [WhiteCoreSim/WhiteCore-Dev#130]
Apr 07 10:42:20 -  ==================== STARTING WhiteCore (x86) ======================
Apr 07 10:42:20 -  ====================================================================
Apr 07 10:42:20 -  [WhiteCoreStartup]: Version: WhiteCore (2015-03-08.d59c3f7)

Apr 07 10:42:20 -  [Network]: Retrieving the external IP address
Apr 07 10:42:20 -  [Network]: Network IP address has been set to 8.38.77.92
Apr 07 10:42:20 -  [BASE HTTP SERVER]: Starting HTTP server on port 8003
Apr 07 10:42:22 -  [VivoxVoice] using vivox server www.osp.vivox.com
Apr 07 10:42:26 -  [VivoxVoice] Admin connection established
Apr 07 10:42:26 -  [VivoxVoice]: plugin enabled
Apr 07 10:42:26 -  [SMTP] Email enabled for Local only
Apr 07 10:42:26 -  [BASE HTTP SERVER]: Starting HTTP server on port 8011
Apr 07 10:42:26 -  [BASE HTTP SERVER]: Starting HTTP server on port 8012
Apr 07 10:42:26 -  [BASE HTTP SERVER]: Starting HTTP server on port 8010
Apr 07 10:42:26 -  [BASE HTTP SERVER]: Starting HTTP server on port 8013
Apr 07 10:42:26 -  [BASE HTTP SERVER]: Starting HTTP server on port 8002
Apr 07 10:42:26 -  [GridServerInfoService]: Adding 1 uri
Apr 07 10:42:26 -  [LIBRARY INVENTORY]: Found previously loaded iar file DefaultInventory/DefaultInventory.iar, ignoring.
Apr 07 10:42:26 -  [WhiteCoreSTARTUP]: Startup completed in 6.0996585
Apr 07 10:42:29 -  [GridServerInfoService]: Adding 7 uris
Apr 07 10:43:27 -  [LLOGIN SERVICE]: Login request for tommy arkright from 162.253.56.17 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Apr 07 10:43:28 -  [LLOGIN SERVICE]: Login failed for user Tommy Arkright, reason: Incorrect password
Apr 07 10:43:46 -  [LLOGIN SERVICE]: Login request for tommy arkright from 162.253.56.17 with user agent Firestorm-Releasex64 4.6.9.42974 starting in last
Apr 07 10:43:46 -  [LLOGIN SERVICE]: All clear. Sending login response to client to login to region Pularas, tried to login to last at <1237.203, 1074.459, 21.32999>.
Apr 07 10:43:51 -  [CapsHandlers]: Handling Seed Cap request at http://8.38.77.92:8003/CAPS/92741606-fdaf-41f6-a3c4-adf16472b0e50000/
Apr 07 10:43:58 -  [VivoxVoice] Created new channel at sip:confctl-3446651@osp.vivox.com for Pularas
Apr 07 10:47:13 -  [Inventory Archiver]: Loading archive ../Data/UserArchives/tommy_arkright.iar to inventory path IAR Import for tommy arkright
Apr 07 10:47:13 -  [ARCHIVER]: Commencing load from archive
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Loading version 0.3 IAR
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 50 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 100 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 150 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 200 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 250 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 300 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 350 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 400 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 450 items...
Apr 07 10:47:13 -  [INVENTORY ARCHIVER]: Restored 500 items...
Apr 07 10:47:14 -  [INVENTORY ARCHIVER]: Restored 550 items...
Apr 07 10:47:14 -  [INVENTORY ARCHIVER]: Restored 600 items...
Apr 07 10:47:14 -  [INVENTORY ARCHIVER]: Restored 650 items...
Apr 07 10:47:14 -  [APPLICATION]: 
APPLICATION EXCEPTION DETECTED

Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at WhiteCore.Modules.Archivers.InventoryArchiveReadRequest.Execute(Boolean loadAll)
   at WhiteCore.Modules.Archivers.InventoryArchiverModule.DearchiveInventory(String firstName, String lastName, String invPath, String loadPath, Dictionary`2 options)
   at WhiteCore.Modules.Archivers.InventoryArchiverModule.HandleLoadIARConsoleCommand(IScene scene, String[] cmdparams)
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath)
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath)
   at WhiteCore.Framework.ConsoleFramework.Commands.Resolve(String[] cmd)
   at WhiteCore.Framework.ConsoleFramework.LocalConsole.ReadLine(String p, Boolean isCommand, Boolean e)
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.Prompt()
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.ReadConsole()
   at WhiteCore.Simulation.Base.SimulationBase.Run()
   at WhiteCore.Simulation.Base.BaseApplication.Startup(IConfigSource originalConfigSource, IConfigSource configSource, ISimulationBase simBase, String[] cmdParameters)

Application is terminating: False

Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result)
Apr 07 10:47:14 -  [SHUTDOWN]: Shutdown processing on main thread complete. 
Apr 07 10:52:49 -  [Console]: Console log level is Info

**Comment by fly-man-** [comment]
Did you make this IAR with an earlier version or is this an IAR from Opensim ?

**Comment by TommyFDNY** [comment]
It's an IAR from opensim/OsGrid. Did I need to use the merge command?

**Comment by TommyFDNY** [comment]
I don't know if there was something corrupt in my inventory. I decided to slim down the way I was saving what I wanted to carry over. IT WORKED!!!

Im flying!!!

save iar tommy arkright "/Commander Aircraft" PASSWORD two.iar

I just am saving each folder I want. Thank you!!! I love you guys!!!

**Comment by greythane** [comment]
Tommy, 
The problem does appear to be something invalid in the full IAR. 
The tests we did seemed to indicate some problem around the "Gas Lamp Stand' item, so I'm interested in anything that causes the system to crash out. (Having the fault causing IAR would be great here)

I'm suspecting that the creation of the IAR is just writing out the data, without out checking to see if the file paths are actually valid.  We cannot control this as this is an OpenSim problem but if it can be determined what is causing the hassle, then steps can be taken to 'work around' or correct it during the loading process of the IAR in WhiteCore.

**Comment by TommyFDNY** [comment]
Well, again you both are amazing. I am sorry I have much to learn, and well I love you guys!
