### ISSUE TITLE
Issues with textures

### ISSUE THREAD

**Issue by WhiteCoreWebUI** [WhiteCoreSim/WhiteCore-Dev#227]
### Steps to reproduce

1. Fetched a .iar from osgrid
2. Restored .iar
3. Dressed up Avatar

### Expected behaviour
Avatar Should look fine

### Actual behaviour

So i was dressing up my avatar for the initial outfits, when i noticed the textures turn totally black and stayed that way, changing viewer or rebaking didnt help, console didnt show any errors i attached a picture
![snapshot_001](https://cloud.githubusercontent.com/assets/9350749/18452877/016deddc-793d-11e6-8f35-64ac4e722d8b.jpg)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**WhiteCore version:**

### Logs

Please make sure that WhiteCore has made an log-file and include a link to it here

**Comment by emperorstarfinder** [comment]
Hmmm, that is a very interesting bug.  Although in the past when avatars have shown up black or other textures such as terrain show up black and not their actual colors or textures it a lot of times amounts to a graphics card issue.  However in this case it could be something going on with that IAR  Recommend trying another IAR from OS grid and then one from outworldz (one of Linda Kellies perhaps) and see if the same problem persists.  If the problem doesn't persist it could just be the IAR (although this is one ive never seen caused by an IAR)

**Comment by WhiteCoreWebUI** [comment]
i just got a new GraphicsCard here are my specs if interested so i dont think thats it (new iar doesnt help either lindakellie ones do the same)
CPU: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (3399.98 MHz)
Memory: 16323 MB
OS Version: Microsoft Windows 8.1 64-bit (Build 9200)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce GTX 750 Ti/PCIe/SSE2
Windows Graphics Driver Version: 21.21.0013.7270
OpenGL Version: 4.5.0 NVIDIA 372.70

**Comment by emperorstarfinder** [comment]
Okay which viewer did you try with this?  Now you have me curious as this is the first time even I have seen this be a problem with an IAR

**Comment by WhiteCoreWebUI** [comment]
Firestorm 32bit , 64bit , ctrlaltstudio, alchemy, singu

**Comment by fly-man-** [comment]
If it's a clean IAR from OsGrid then I think it has to do with the basic textures they have. Those aren't included in an IAR export.

**Comment by emperorstarfinder** [comment]
I tend to agree here.  After speaking with him further he indicates that the same is happening with Linda Kelly's IARs (zadaroo) as well.  I haven't had a chance to test this just yet myself.

**Comment by WhiteCoreWebUI** [comment]
Normally i would agree with fly-man- but after around 15 minutes the textures show up, to confirm this i created clothes myself on my computer and made a iar from that uploaded it to the server and it did the same, so the iar was created with WC RC2 and loaded to WC RC2 and i had this issue

**Comment by fly-man-** [comment]
@WhiteCoreWebUI You might know what I would normally say next: Can you make sure you have the latest master, make sure you have a (server / region) log file so we can see what's happening

**Comment by emperorstarfinder** [comment]
I did a little testing on this last night and will be doing some more tonight.  Interestingly there does appear to be a problem but there is nothing showing up that i can see in the logs (even with log level debug) to suggest a critical problem with texture rendering.  Using the latest master last night myself I actually logged in to see no sky (was fixed after setting the viewer's environmental setting to midday).  Avatar texture rendering appears to be slow as well.  When logged in for approximately five minutes (after which the inventory should have synced and fetched even with the default avatar) the avatar remains grey until after rebaking the avatar.  So while I could not re-produce his exact problem myself last night there does appear to be an issue except the question is what.  I will continue more testing tonight in hopes of shedding more light onto this issue.

**Comment by emperorstarfinder** [comment]
After further testing I have now re-produced WhiteCoreWebUI's issue as well.  This appears to date back at least to https://github.com/WhiteCoreSim/WhiteCore-Dev/releases/tag/0.9.3.0810

When you load the IAR (for the purpose of this test I used an IAR from zadaroo.com which I know works.  After attaching an article of clothing the avatar in fact does go black.  However it recovers when attaching or wearing something else.  

One of the errors found is:

Sep 15 12:44:47 -  [Serializer]: exception while parsing StateSaveXML: System.Xml.XmlException: 'Element' is an invalid XmlNodeType. Line 1, position 5504.
   at System.Xml.XmlReader.ReadEndElement()
   at WhiteCore.Region.Serialization.SceneObjectSerializer.ReadStateSave(SceneObjectPart obj, XmlTextReader reader, Type sopType) in C:\Users\virtu\Desktop\WhiteCore-Dev-0.9.3.0810\WhiteCore\Region\Serialization\SceneObjectSerializer.cs:line 1752
   at WhiteCore.Region.Serialization.SceneObjectSerializer.<>c__DisplayClass16_0.<.ctor>b__40(SceneObjectPart sop, XmlTextReader xml) in C:\Users\virtu\Desktop\WhiteCore-Dev-0.9.3.0810\WhiteCore\Region\Serialization\SceneObjectSerializer.cs:line 473
   at WhiteCore.Region.Serialization.SceneObjectSerializer.Xml2ToSOP(XmlTextReader reader) in C:\Users\virtu\Desktop\WhiteCore-Dev-0.9.3.0810\WhiteCore\Region\Serialization\SceneObjectSerializer.cs:line 1050

This occurs when attaching or wearing items from the IAR.  Because this is an old IAR from Linda Kellie and has been working up until now there is no reason to believe that it is the IAR itself.  

Result: Bug confirmed on Windows

**Comment by greythane** [comment]
The IAR formatting/serialization has not chafed for quit a while. 
Could I get some specific IAR details of which ones were used please so i can recheck this ( rather than the generic .. Old Linda Kelly one, downside from zardoo )

... And we are talking about avatar attachments from an IAR and not an OAR? Just checking😊

**Comment by emperorstarfinder** [comment]
The Avatar Attachments correct.  I tried the full avatar IAR from zadaroo.com as historically there have always been issues with the OSGrid IARs.  the error i posted happens during attachment and the avatar goes all black as depicted by WhiteCoreWebUI's picture.  http://zadaroo.com/?page_id=1584

**Comment by emperorstarfinder** [comment]
Okay @greythane your comment got me thinking a bit more.  So this morning I tested with just creating a plan object (i did not edit the object in any way just a plain default cube) and got the same error.  So I think now it is safe to say it is not the IARs per say but something with serialization  If this helps give some clues perhaps

**Comment by WhiteCoreWebUI** [comment]
Ok @greythane  , @emperorstarfinder  and me been digging a bit around this seems to be related in a recent viewer change it seems that LL pushed out global SSA to the Grid, now the viewer debug console throws out "Region does not support baking" as soon as you attach a object and you turn black, reverting to a older viewer i.e Singularity 1.8.6 6156 Removes the issue, so it seems the viewer is looking for something we dont have yet

**Comment by greythane** [comment]
Thanks ThunderLife,
I'll have a look at the viewer code to see what reply it is expecting. This is obviously one that needs to be corrected quickly

**Comment by fly-man-** [comment]
@WhiteCoreWebUI Please use the latest viewer to see if the issue is still appearing. I've had a lot of issues with the older Singularity.

Do know that starting 0.9.5 any viewer that isn't conforming to the v3 standard will have issues as we're going for the v3 compatibility for Marketplace and other things.

**Comment by emperorstarfinder** [comment]
This isn't related to the viewer.  By setting CSJ2K = false to CSJ2K = true in:

Grid = Config/Grid/ServerConfiguration/Modules/AssetCache.ini
Sim = Config/Sim/Modules/Advanced.ini

the black avatars should go away and be normal in all cases.  Additionally this assumes your using the latest from master.  This has now been tested on Windows and Linux and confirmed to be working normally. Additionally for those who receive a Unknown Layer Type!88 error this will also correct that problem as well.  The Unknown Layer Type!88 error is not frequent but is due to textures not decoding correctly.
